In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('both_combined.csv')

C:\Users\Sulav Bhandari\AppData\Local\Temp\ipykernel_11976\3696648438.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('both_combined.csv')


In [3]:
data.shape

(1592124, 17)

In [4]:
data = data[data['latitude'] >= 26]

In [5]:
data.shape

(866554, 17)

In [6]:
data.head()

latitude  longitude  brightness  scan  track    acq_date  acq_time  \
0   28.2590    85.1385       319.5   1.0    1.0  2013-01-01       511   
1   28.3517    82.9548       308.4   1.0    1.0  2013-01-01       511   
2   29.0575    82.4327       308.6   1.1    1.0  2013-01-01       511   
3   28.4146    84.5473       304.5   1.0    1.0  2013-01-01       511   
4   29.0424    81.9060       302.7   2.8    1.6  2013-01-01       824   

  satellite instrument confidence  version  bright_t31   frp daynight  type  \
0     Terra      MODIS         70      6.2       295.5  18.0        D     0   
1     Terra      MODIS         67      6.2       288.2  10.5        D     0   
2     Terra      MODIS         33      6.2       287.3   9.1        D     0   
3     Terra      MODIS         32      6.2       291.5   8.1        D     0   
4      Aqua      MODIS         41      6.2       290.8  24.7        D     0   

   bright_ti4  bright_ti5  
0         NaN         NaN  
1         NaN         NaN  
2         NaN         NaN  
3         NaN         NaN  
4         NaN         NaN

In [7]:
data.tail()

latitude  longitude  brightness  scan  track    acq_date  acq_time  \
1592119  27.125383  84.859642         NaN  0.39   0.36  2021-12-25       724   
1592120  27.128704  84.858986         NaN  0.39   0.36  2021-12-25       724   
1592121  28.698627  80.359848         NaN  0.54   0.42  2021-12-25       724   
1592122  28.820669  80.171555         NaN  0.55   0.43  2021-12-25       724   
1592123  29.633783  81.807281         NaN  0.43   0.46  2021-12-31       712   

        satellite instrument confidence  version  bright_t31   frp daynight  \
1592119         N      VIIRS          n      1.0         NaN  2.05        D   
1592120         N      VIIRS          n      1.0         NaN  2.05        D   
1592121         N      VIIRS          n      1.0         NaN  8.72        D   
1592122         N      VIIRS          n      1.0         NaN  3.87        D   
1592123         N      VIIRS          n      1.0         NaN  3.30        D   

         type  bright_ti4  bright_ti5  
1592119     0      332.21      296.39  
1592120     0      331.20      293.93  
1592121     0      330.97      294.96  
1592122     0      332.00      296.71  
1592123     0      329.38      294.68

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 866554 entries, 0 to 1592123
Data columns (total 17 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   latitude    866554 non-null  float64
 1   longitude   866554 non-null  float64
 2   brightness  265120 non-null  float64
 3   scan        866554 non-null  float64
 4   track       866554 non-null  float64
 5   acq_date    866554 non-null  object 
 6   acq_time    866554 non-null  int64  
 7   satellite   866554 non-null  object 
 8   instrument  866554 non-null  object 
 9   confidence  866554 non-null  object 
 10  version     866554 non-null  float64
 11  bright_t31  265120 non-null  float64
 12  frp         866554 non-null  float64
 13  daynight    866554 non-null  object 
 14  type        866554 non-null  int64  
 15  bright_ti4  601434 non-null  float64
 16  bright_ti5  601434 non-null  float64
dtypes: float64(10), int64(2), object(5)
memory usage: 119.0+ MB


In [9]:
data.columns

Index(['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'type', 'bright_ti4', 'bright_ti5'],
      dtype='object')

In [10]:
data.isnull().sum()

latitude           0
longitude          0
brightness    601434
scan               0
track              0
acq_date           0
acq_time           0
satellite          0
instrument         0
confidence         0
version            0
bright_t31    601434
frp                0
daynight           0
type               0
bright_ti4    265120
bright_ti5    265120
dtype: int64

In [11]:
data.shape

(866554, 17)

In [12]:
data.describe()

latitude      longitude     brightness           scan  \
count  866554.000000  866554.000000  265120.000000  866554.000000   
mean       28.101421      83.233290     319.359122       0.734559   
std         0.766397       2.083861      11.706690       0.549596   
min        26.377500      80.031349     300.000000       0.320000   
25%        27.495331      81.492989     310.700000       0.400000   
50%        28.046300      82.696625     319.400000       0.480000   
75%        28.725700      84.865585     325.700000       1.000000   
max        30.266900      88.161278     477.200000       4.800000   

               track       acq_time        version     bright_t31  \
count  866554.000000  866554.000000  866554.000000  265120.000000   
mean        0.665229    1252.200913       2.576427     300.253998   
std         0.344149     629.577855       2.374736       8.304995   
min         0.360000     404.000000       1.000000     265.200000   
25%         0.380000     730.000000       1.000000     293.900000   
50%         0.500000     807.000000       1.000000     301.200000   
75%         1.000000    2001.000000       6.030000     306.600000   
max         2.000000    2128.000000       6.200000     328.000000   

                 frp           type     bright_ti4     bright_ti5  
count  866554.000000  866554.000000  601434.000000  601434.000000  
mean        8.951506       0.002412     323.106973     296.779639  
std        21.703668       0.084319      17.755905       8.902940  
min         0.000000       0.000000     208.000000     234.550000  
25%         1.630000       0.000000     306.260000     290.690000  
50%         4.230000       0.000000     323.040000     295.090000  
75%         9.500000       0.000000     337.540000     303.960000  
max      2479.900000       3.000000     367.000000     367.990000

In [13]:
data['satellite'].unique()

array(['Terra', 'Aqua', 'N'], dtype=object)

In [14]:
data.instrument.unique()

array(['MODIS', 'VIIRS'], dtype=object)

In [15]:
data.confidence.count()

866554

In [16]:
def map_confidence(confidence):    

    if (confidence == 'l'):
        return 30
    elif (confidence == 'n'):
        return 60
    elif (confidence == 'h'):
        return 90
    #convert the string and int to int
    else:
        return int(confidence)


# Apply the mapping function to the 'confidence' column
data['confidence'] = data['confidence'].apply(map_confidence)

In [17]:
# converting string to int
data['confidence'] = data['confidence'].astype(int)

In [18]:
data.confidence.unique()

array([ 70,  67,  33,  32,  41,  86,  76,  74,  56,  84,  83,  72,  80,
        43, 100,  87,  46,  71,  36,  66,  39,  21,   9,  68,  77,  29,
        15,  50,  89,  26,  25,  51,  99,  44,  58,   0,  73,  92,  93,
        62,  37,  13,  40,  27,  48,  79,  20,  60,  52,  59,  45,  85,
        82,  54,  35,  57,  63,  53,  75,  55,  65,  30,  61,  42,  81,
        34,  91,  78,  96,  47,  49,  64,  24,  28,  23,  69,  19,  38,
        97,  31,  94,  95,  17,  88,  22,   7,  11,   6,  90,  10,  98,
         5,  18,  12,   2,  14,  16,   4,   8,   3,   1])

In [19]:
# convert all the values in confidence column to numeric
# data['confidence'] = pd.to_numeric(data['confidence'], errors='coerce')

In [20]:
data.confidence.count()

866554

In [21]:
data.daynight.unique()

array(['D', 'N', '1', '0'], dtype=object)

In [22]:
def map_confidence(daynight):
    if (daynight == 'D'):
        return 1
    elif (daynight == 'N'):
        return 0
    else:
        return int(daynight)



# Apply the mapping function to the 'confidence' column
data['daynight'] = data['daynight'].apply(map_confidence)

In [23]:
data.daynight.unique()

array([1, 0], dtype=int64)

# One Hot Encoder

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
label_encoder = LabelEncoder()
data['confidence'] = label_encoder.fit_transform(data['confidence'])



In [26]:
data.type.unique()

array([0, 2, 3], dtype=int64)

In [27]:
data.head()

latitude  longitude  brightness  scan  track    acq_date  acq_time  \
0   28.2590    85.1385       319.5   1.0    1.0  2013-01-01       511   
1   28.3517    82.9548       308.4   1.0    1.0  2013-01-01       511   
2   29.0575    82.4327       308.6   1.1    1.0  2013-01-01       511   
3   28.4146    84.5473       304.5   1.0    1.0  2013-01-01       511   
4   29.0424    81.9060       302.7   2.8    1.6  2013-01-01       824   

  satellite instrument  confidence  version  bright_t31   frp  daynight  type  \
0     Terra      MODIS          70      6.2       295.5  18.0         1     0   
1     Terra      MODIS          67      6.2       288.2  10.5         1     0   
2     Terra      MODIS          33      6.2       287.3   9.1         1     0   
3     Terra      MODIS          32      6.2       291.5   8.1         1     0   
4      Aqua      MODIS          41      6.2       290.8  24.7         1     0   

   bright_ti4  bright_ti5  
0         NaN         NaN  
1         NaN         NaN  
2         NaN         NaN  
3         NaN         NaN  
4         NaN         NaN

In [28]:
#onverting frp to int roundig to nearest value
data['frp'] = data['frp'].astype(int)

In [29]:
data['acq_date'] = pd.to_datetime(data['acq_date'])
data['month'] = data['acq_date'].dt.month
data['day'] = ((data['acq_date'].dt.day))
data.tail()

latitude  longitude  brightness  scan  track   acq_date  acq_time  \
1592119  27.125383  84.859642         NaN  0.39   0.36 2021-12-25       724   
1592120  27.128704  84.858986         NaN  0.39   0.36 2021-12-25       724   
1592121  28.698627  80.359848         NaN  0.54   0.42 2021-12-25       724   
1592122  28.820669  80.171555         NaN  0.55   0.43 2021-12-25       724   
1592123  29.633783  81.807281         NaN  0.43   0.46 2021-12-31       712   

        satellite instrument  confidence  version  bright_t31  frp  daynight  \
1592119         N      VIIRS          60      1.0         NaN    2         1   
1592120         N      VIIRS          60      1.0         NaN    2         1   
1592121         N      VIIRS          60      1.0         NaN    8         1   
1592122         N      VIIRS          60      1.0         NaN    3         1   
1592123         N      VIIRS          60      1.0         NaN    3         1   

         type  bright_ti4  bright_ti5  month  day  
1592119     0      332.21      296.39     12   25  
1592120     0      331.20      293.93     12   25  
1592121     0      330.97      294.96     12   25  
1592122     0      332.00      296.71     12   25  
1592123     0      329.38      294.68     12   31

In [30]:
data['month'].value_counts()

4     446374
3     185996
5     119308
2      30486
12     27308
1      26382
6      14512
11     13584
10      1992
9        298
8        176
7        138
Name: month, dtype: int64

# khai k ho kei mildaina

In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [32]:
X = data[['latitude', 'longitude', 'month', 'day']]

In [33]:
Y = data[['type']] 

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

### Testing all algorithms

In [35]:
# Checking with other algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [36]:
svc = SVC(kernel='sigmoid',gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear',penalty='l1')
rfc = RandomForestClassifier(n_estimators=50,random_state=2)
abc = AdaBoostClassifier(n_estimators=50,random_state=2)
bc = BaggingClassifier(n_estimators=50,random_state=2)
etc = ExtraTreesClassifier(n_estimators=50,random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50)


In [37]:
# creating a dictionary of all the models
clfs = {
    "SVC": svc,
    "KN": knc,
    "NB": mnb,
    "DT": dtc,
    "LR": lrc,
    # "RF": rfc,
    "AdaBoost": abc,
    "BgC": bc,
    "ETC": etc,
    "GBDT": gbdt,
    "xgb": xgb,
}


In [38]:
def train_classifier(clf, X_train, y_train,X_test,y_test):    
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    return accuracy

In [39]:
# # checking with one algorithm
# train_classifier(rfc,X_train,y_train,X_test,y_test) 

In [40]:
train_classifier(rfc,X_train,y_train,X_test,y_test)

C:\Users\Sulav Bhandari\AppData\Local\Temp\ipykernel_11976\537262703.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train, y_train)


0.9999019104384603

In [41]:
# convert the model_rfc to pickle file
import pickle
pickle.dump(rfc, open('model_type_final.pkl', 'wb'))